"""
MarkJobComplete — call after all generation files have been created.

Updates the job record in jobs.db with the list of generated file paths,
marks the job as 'done', and sends the completion email to the teacher
if an email address was recorded when the job was created.
"""
import sys
from pathlib import Path

from agency_swarm.tools import BaseTool
from pydantic import Field

_cogniesl_root = str(Path(__file__).parent.parent.parent)
if _cogniesl_root not in sys.path:
    sys.path.insert(0, _cogniesl_root)

from agent import jobs as _jobs
from agent.email_sender import send_completion_email
from agent.master_repository import get_combination_key, add_to_cache

# Auth db may not be available during testing without auth setup
try:
    from auth.db import create_material
    _auth_db_available = True
except ImportError:
    _auth_db_available = False


class MarkJobComplete(BaseTool):
    """
    Mark a generation job as complete and trigger the delivery email.

    Call this AFTER BuildPptxFromHtmlSlides (and CreateDocument/ConvertDocument
    for worksheet and activity guide) have all finished successfully.

    Lists only files that were actually generated — omit files for formats
    that were not requested.
    """

    job_id: str = Field(
        ...,
        description="The job_id returned by QueueGenerationJob at the start of generation.",
    )
    project_name: str = Field(
        ...,
        description="Project folder name (e.g. 'present_perfect_french_adults').",
    )
    html_bundle_path: str | None = Field(
        default=None,
        description=(
            "Relative path to the offline HTML bundle — the primary slide deliverable. "
            "e.g. './mnt/present_perfect_french_adults/presentations/present_perfect_french_adults.html'"
        ),
    )
    pptx_path: str | None = Field(
        default=None,
        description=(
            "Relative path to PPTX — only set if teacher explicitly requested PowerPoint format. "
            "e.g. './mnt/present_perfect_french_adults/presentations/present_perfect_french_adults.pptx'"
        ),
    )
    worksheet_pdf_path: str | None = Field(
        default=None,
        description="Relative path to worksheet PDF if a worksheet was generated.",
    )
    worksheet_docx_path: str | None = Field(
        default=None,
        description="Relative path to worksheet DOCX if a worksheet was generated.",
    )
    activity_pdf_path: str | None = Field(
        default=None,
        description="Relative path to activity guide PDF if an activity guide was generated.",
    )
    activity_docx_path: str | None = Field(
        default=None,
        description="Relative path to activity guide DOCX if an activity guide was generated.",
    )
    flashcard_pdf_path: str | None = Field(
        default=None,
        description="Relative path to flashcard PDF if flashcards were generated.",
    )
    progress_tracker_pdf_path: str | None = Field(
        default=None,
        description="Relative path to student progress tracker PDF if generated.",
    )
    snapshot_path: str | None = Field(
        default=None,
        description=(
            "Absolute path to the 1080×1080 PNG slide preview image generated by "
            "SnapSlideForEmail. If provided, it is embedded in the delivery email."
        ),
    )
    slide_count: int = Field(
        default=0,
        description="Total number of slides generated (0 if no slides).",
    )

    def run(self) -> str:
        # Collect non-None file paths
        file_paths = [
            p for p in [
                self.html_bundle_path,
                self.pptx_path,
                self.worksheet_pdf_path,
                self.worksheet_docx_path,
                self.activity_pdf_path,
                self.activity_docx_path,
                self.flashcard_pdf_path,
                self.progress_tracker_pdf_path,
            ]
            if p
        ]

        # Update job record
        _jobs.mark_done(self.job_id, file_paths)

        # Send email if address was recorded
        job = _jobs.get_job(self.job_id)
        email_sent = False
        if job and job.get("email"):
            email_sent = send_completion_email(
                to_email=job["email"],
                job_id=self.job_id,
                project_name=self.project_name,
                grammar_point=job.get("grammar_point", ""),
                l1_languages=job.get("l1_languages", ""),
                file_paths=file_paths,
                snapshot_path=self.snapshot_path,
            )

        # Write to materials table if user was authenticated
        if _auth_db_available and job and job.get("user_id"):
            try:
                formats_raw = job.get("formats", [])
                formats_str = ", ".join(formats_raw) if isinstance(formats_raw, list) else str(formats_raw)
                create_material(
                    user_id=job["user_id"],
                    job_id=self.job_id,
                    project_name=self.project_name,
                    grammar_point=job.get("grammar_point", ""),
                    l1_languages=job.get("l1_languages", ""),
                    age_group=job.get("age_group", "adults"),
                    formats=formats_str,
                    slide_count=self.slide_count,
                    html_bundle_path=self.html_bundle_path,
                    pptx_path=self.pptx_path,
                    worksheet_pdf_path=self.worksheet_pdf_path,
                    worksheet_docx_path=self.worksheet_docx_path,
                    activity_pdf_path=self.activity_pdf_path,
                    activity_docx_path=self.activity_docx_path,
                    flashcard_pdf_path=self.flashcard_pdf_path,
                    progress_tracker_pdf_path=self.progress_tracker_pdf_path,
                )
            except Exception as e:
                # Non-fatal — job is still done, just not in materials library
                import logging
                logging.getLogger(__name__).warning(f"Failed to write materials row: {e}")

        result = f"Job {self.job_id} marked complete. {len(file_paths)} file(s) registered."
        if email_sent:
            result += f" Completion email sent to {job['email']}."
        elif job and job.get("email"):
            result += " (Email send failed — check RESEND_API_KEY in .env.)"
        else:
            result += " No email address on file — skipping notification."

        # ── Master Repository: add to cache for future requests ───────────────
        # Use html_bundle_path as the primary indicator (pptx is opt-in, rarely set)
        _primary_path = self.html_bundle_path or self.pptx_path
        if job and _primary_path:
            try:
                _l1_list = [l.strip() for l in (job.get("l1_languages") or "").split(",") if l.strip()]
                _age = job.get("age_group", "adults")
                _level = job.get("level", "b1")  # may not exist in older jobs
                if len(_l1_list) == 1:
                    _cache_key = get_combination_key(
                        grammar=job.get("grammar_point", ""),
                        l1=_l1_list[0],
                        age=_age,
                        level=_level,
                    )
                    _ref_file = Path(_primary_path)
                    if _ref_file.exists() and _ref_file.parent.exists():
                        stored = add_to_cache(_cache_key, _ref_file.parent)
                        if stored:
                            result += f" Stored in Master Repository cache ({_cache_key})."
            except Exception:
                pass  # Cache miss is non-fatal

        return result
