import { Container } from "@/components/ui/Container";
import { Section } from "@/components/ui/Section";

export const metadata = {
  title: "AI Disclaimer — CogniESL",
  description: "Important information about AI-generated content from CogniESL.",
};

export default function AIDisclaimerPage() {
  return (
    <Section className="pt-28 lg:pt-32 pb-12">
      <Container size="md">
        <h1 className="text-3xl font-bold text-neutral-900 mb-2">AI Disclaimer</h1>
        <p className="text-sm text-neutral-500 mb-8">Last updated: {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</p>

        <div className="space-y-6 text-neutral-600 leading-relaxed">
          <div className="bg-amber-50 border border-amber-200 rounded-xl p-6 mb-8">
            <h2 className="text-lg font-semibold text-amber-800 mb-2">⚠️ Important Notice</h2>
            <p className="text-amber-700">All materials generated by CogniESL are created using artificial intelligence. While we strive for accuracy, <strong>all materials should be reviewed by a qualified teacher before classroom use.</strong></p>
          </div>

          <section>
            <h2 className="text-xl font-semibold text-neutral-800 mb-3">AI-Generated Content</h2>
            <p>CogniESL uses advanced AI models to generate teaching materials. These models may occasionally produce errors or inappropriate content. Materials should be treated as a first draft, not a final product.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-neutral-800 mb-3">Teacher Responsibility</h2>
            <p>You are responsible for reviewing all generated materials for accuracy, adapting them to your students&apos; needs, and using professional judgment in all teaching decisions.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-neutral-800 mb-3">L1 Interference Information</h2>
            <p>Our L1 interference patterns are based on linguistic research. However, not all students from a language background will make the same errors. Individual variation and proficiency level affect language transfer.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-neutral-800 mb-3">Feedback</h2>
            <p>If you find errors or have suggestions, please let us know at <a href="mailto:feedback@cogniesl.com" className="text-primary-500 hover:underline">feedback@cogniesl.com</a>.</p>
          </section>
        </div>
      </Container>
    </Section>
  );
}
