import { Badge } from "@/components/ui/Badge";
import { Container } from "@/components/ui/Container";
import { Section } from "@/components/ui/Section";
import { Button } from "@/components/ui/Button";
import Link from "next/link";

export const metadata = {
  title: "Sample Materials — CogniESL",
  description: "See examples of ESL teaching materials generated by CogniESL with L1 interference intelligence.",
};

const samples = [
  {
    type: "Slide Deck (PPTX)",
    icon: "📊",
    title: "Present Perfect vs. Simple Past",
    description: "15-slide PPTX deck with CCQs, formation rules, L1 Oracle slides for Spanish speakers highlighting the preterite/present perfect confusion, and practice activities with speaker notes throughout.",
    l1: "Spanish",
    detail: "15 slides · PPTX download",
    color: "primary" as const,
    featured: true,
  },
  {
    type: "Worksheet",
    icon: "📝",
    title: "Articles: A, An, The",
    description: "Multi-section worksheet targeting article usage for Mandarin and Korean speakers — two languages without an article system. Sections A–E plus a full answer key with L1 explanations.",
    l1: "Mandarin & Korean",
    detail: "Sections A–E · Answer key included",
    color: "secondary" as const,
    featured: true,
  },
  {
    type: "Activity Guide",
    icon: "🎮",
    title: "Third Conditional: Regrets & Hypotheticals",
    description: "Step-by-step classroom activity guide with teacher script, differentiation notes for multiple levels, and L1-specific stumbling blocks for Chinese and Japanese speakers.",
    l1: "Chinese & Japanese",
    detail: "Teacher script · Differentiation tips",
    color: "accent" as const,
    featured: false,
  },
];

const colorMap = {
  primary: "bg-primary-100 dark:bg-primary-900/30 text-primary-700 dark:text-primary-300",
  secondary: "bg-secondary-100 dark:bg-secondary-900/30 text-secondary-700 dark:text-secondary-300",
  accent: "bg-accent-100 dark:bg-accent-900/30 text-accent-700 dark:text-accent-300",
  success: "bg-success-100 dark:bg-success-900/30 text-success-700 dark:text-success-300",
};

export default function SamplesPage() {
  return (
    <>
      <Section className="pt-28 lg:pt-32 pb-12 " background="neutral">
        <Container size="md">
          <div className="text-center">
            <Badge variant="primary" className="mb-4">Sample Materials</Badge>
            <h1 className="text-4xl sm:text-5xl font-bold text-neutral-900 dark:text-neutral-50 mb-4">
              See What CogniESL <span className="gradient-text">Actually Makes</span>
            </h1>
            <p className="text-lg text-neutral-600 dark:text-neutral-400 max-w-2xl mx-auto">
              These are representative examples of the three formats CogniESL generates — slides, worksheets, and activity guides. Each one is tailored to the grammar point and native language(s) you specify.
            </p>
          </div>
        </Container>
      </Section>

      <Section>
        <Container>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6 max-w-6xl mx-auto mb-16">
            {samples.map((sample) => (
              <div
                key={sample.title}
                className="bg-white dark:bg-neutral-900 rounded-2xl p-6 border border-neutral-200/80 dark:border-neutral-800 hover:shadow-card-hover transition-all duration-300"
              >
                <div className="flex items-center gap-2 mb-4">
                  <span className="text-2xl">{sample.icon}</span>
                  <span className={`text-xs font-medium px-2.5 py-1 rounded-full ${colorMap[sample.color]}`}>
                    {sample.type}
                  </span>
                </div>
                <h3 className="font-heading text-lg font-semibold text-neutral-900 dark:text-neutral-100 mb-2">
                  {sample.title}
                </h3>
                <p className="text-neutral-600 dark:text-neutral-400 text-sm leading-relaxed mb-4">
                  {sample.description}
                </p>
                <div className="border-t border-neutral-100 dark:border-neutral-800 pt-4 flex items-center justify-between">
                  <span className="text-xs text-neutral-500 dark:text-neutral-400">L1: {sample.l1}</span>
                  <span className="text-xs text-neutral-400 dark:text-neutral-500">{sample.detail}</span>
                </div>
              </div>
            ))}
          </div>

          {/* Explainer */}
          <div className="max-w-3xl mx-auto bg-neutral-50 dark:bg-neutral-800/50 rounded-2xl p-8 border border-neutral-200/80 dark:border-neutral-700 mb-12">
            <h2 className="font-heading text-xl font-semibold text-neutral-900 dark:text-neutral-100 mb-4">
              What&apos;s inside each format?
            </h2>
            <div className="grid md:grid-cols-3 gap-6 text-sm">
              <div>
                <div className="font-semibold text-neutral-900 dark:text-neutral-100 mb-2">📊 Slide Deck</div>
                <ul className="space-y-1 text-neutral-600 dark:text-neutral-400">
                  <li>• Hook slide (real-world context)</li>
                  <li>• Concept Check Questions (CCQs)</li>
                  <li>• Formation rules with examples</li>
                  <li>• L1 Oracle slide(s)</li>
                  <li>• Practice &amp; production slides</li>
                  <li>• Speaker notes on every slide</li>
                </ul>
              </div>
              <div>
                <div className="font-semibold text-neutral-900 dark:text-neutral-100 mb-2">📝 Worksheet</div>
                <ul className="space-y-1 text-neutral-600 dark:text-neutral-400">
                  <li>• Section A: Comprehension check</li>
                  <li>• Section B: Guided practice</li>
                  <li>• Section C: Error correction</li>
                  <li>• Section D: Production</li>
                  <li>• Section E: Extension</li>
                  <li>• Full answer key</li>
                </ul>
              </div>
              <div>
                <div className="font-semibold text-neutral-900 dark:text-neutral-100 mb-2">🎮 Activity Guide</div>
                <ul className="space-y-1 text-neutral-600 dark:text-neutral-400">
                  <li>• Step-by-step teacher script</li>
                  <li>• Setup &amp; timing instructions</li>
                  <li>• L1-specific watch-fors</li>
                  <li>• Differentiation for lower levels</li>
                  <li>• Extension for advanced students</li>
                  <li>• Student-facing materials</li>
                </ul>
              </div>
            </div>
          </div>

          <div className="text-center">
            <p className="text-neutral-600 dark:text-neutral-400 mb-6">
              Ready to generate your own? Join the waitlist — early access is free.
            </p>
            <Button size="lg" asChild>
              <Link href="/#waitlist">Get Early Access</Link>
            </Button>
          </div>
        </Container>
      </Section>
    </>
  );
}
